//! The connection editor — a modal over whichever page is open.
//!
//! What it edits is an intent, not a setting: the checkboxes are exactly the CLI's connect flags
//! (`--p2p`, `--securecore`, `--tor`), the country and city are picked from the two lists the CLI
//! prints, and port forwarding is ours. The preview at the bottom is generated by the launcher
//! itself, so what the user reads is the argv that will actually run.

use iced::widget::{Space, button, checkbox, column, container, row, scrollable, text, text_input};
use iced::{Alignment, Element, Font, Length, Padding, Theme};

use protonvpn_core::launcher::Intent;

use crate::app::{App, ConnectionEditor, EditorFlag, Message};
use crate::theme;
use crate::widgets::{self, Tone};

pub(crate) fn view<'a>(app: &'a App, editor: &'a ConnectionEditor) -> Element<'a, Message> {
    let heading = if editor.editing.is_some() {
        app.i18n.editor_title_edit()
    } else {
        app.i18n.editor_title_new()
    };

    let header = row![
        column![
            widgets::eyebrow(heading),
            widgets::muted(app.i18n.editor_subtitle()),
        ]
        .spacing(2)
        .width(Length::Fill),
        button(text("×").size(16))
            .padding(Padding::from([2, 8]))
            .style(theme::ghost(theme::TEXT_MUTED, false))
            .on_press(Message::EditorCancel),
    ]
    .align_y(Alignment::Center);

    let name = column![
        text(app.i18n.editor_name_label()).size(13),
        text_input(&app.i18n.editor_name_placeholder(), &editor.name)
            .on_input(Message::EditorName)
            .padding(Padding::from([9, 12]))
            .width(Length::Fill),
    ]
    .spacing(6);

    let flags = row(EditorFlag::ALL
        .iter()
        .map(|flag| {
            let checked = match flag {
                EditorFlag::P2p => editor.p2p,
                EditorFlag::SecureCore => editor.secure_core,
                EditorFlag::Tor => editor.tor,
                EditorFlag::PortForwarding => editor.port_forwarding,
            };
            checkbox(checked)
                .label(flag.label(&app.i18n))
                .text_size(13)
                .on_toggle(move |value| Message::EditorFlag(*flag, value))
                .into()
        })
        .collect::<Vec<Element<'_, Message>>>())
    .spacing(18)
    .align_y(Alignment::Center);

    let body = row![
        container(country_panel(app, editor))
            .width(Length::FillPortion(3))
            .height(Length::Fixed(330.0)),
        container(city_panel(app, editor))
            .width(Length::FillPortion(2))
            .height(Length::Fixed(330.0))
            .padding(Padding::from([0, 0])),
    ]
    .spacing(14);

    // The preview is the launcher's own argv, verbatim: it is data, and it is shown exactly as it
    // will be executed, in every language. Only the code around it is ours.
    let preview = container(
        text(format!(
            "$ {}",
            Intent::Connect(editor.target()).argv().join(" ")
        ))
        .size(12)
        .font(Font::MONOSPACE)
        .style(|_: &Theme| iced::widget::text::Style {
            color: Some(theme::TEXT_MUTED),
        }),
    )
    .padding(Padding::from([8, 12]))
    .width(Length::Fill)
    .style(theme::flat_card);

    let buttons = row![
        button(text(app.i18n.editor_cancel()).size(13))
            .padding(Padding::from([8, 16]))
            .style(theme::outlined(theme::BORDER, theme::TEXT))
            .on_press(Message::EditorCancel),
        button(text(app.i18n.editor_save()).size(13))
            .padding(Padding::from([8, 18]))
            .style(theme::filled(theme::ACCENT))
            .on_press(Message::EditorSave),
    ]
    .spacing(8);

    let footer = row![
        preview,
        Space::new()
            .width(Length::Fixed(12.0))
            .height(Length::Fixed(1.0)),
        buttons,
    ]
    .align_y(Alignment::Center)
    .width(Length::Fill);

    let modal = container(
        column![header, widgets::separator(), name, flags, body, footer]
            .spacing(14)
            .padding(Padding::from([18, 20])),
    )
    .width(Length::Fixed(760.0))
    .style(theme::card);

    container(modal)
        .padding(Padding::from([28, 28]))
        .width(Length::Fill)
        .height(Length::Fill)
        .center_x(Length::Fill)
        .center_y(Length::Fill)
        .style(theme::backdrop)
        .into()
}

fn country_panel<'a>(app: &'a App, editor: &'a ConnectionEditor) -> Element<'a, Message> {
    let search = text_input(
        &app.i18n.editor_search_placeholder(),
        &editor.country_filter,
    )
    .on_input(Message::EditorFilter)
    .padding(Padding::from([8, 12]));

    let mut list = column![country_option(
        None,
        app.i18n.editor_any_country(),
        app.i18n.editor_any_country_hint(),
        editor.country.is_none(),
    )]
    .spacing(4);

    let Some(observation) = &app.shared.state.countries else {
        list = list.push(widgets::note(app.i18n.editor_countries_pending()));
        // The console sits behind this dialog, so if the CLI refused, say so here rather than
        // leaving an empty list and no reason for it.
        if let Some(error) = &app.shared.state.last_error {
            list = list.push(widgets::note(
                app.i18n.editor_country_error(&error.value.message),
            ));
        }
        return column![search, scrollable(list).height(Length::Fill)]
            .spacing(10)
            .into();
    };

    let needle = editor.country_filter.trim().to_lowercase();
    let countries: Vec<&protonvpn_core::model::Country> = observation
        .value
        .iter()
        .filter(|country| {
            needle.is_empty()
                || country.name.to_lowercase().contains(&needle)
                || country.code.to_lowercase().contains(&needle)
        })
        .collect();

    if countries.is_empty() {
        list = list.push(widgets::faint(app.i18n.editor_country_empty()));
    }
    for country in countries {
        list = list.push(country_option(
            Some(country.code.clone()),
            &country.name,
            &country.code,
            editor.country.as_deref() == Some(country.code.as_str()),
        ));
    }

    column![
        search,
        scrollable(list).height(Length::Fill),
        widgets::faint(app.countries_age().unwrap_or_else(|| "—".into())),
    ]
    .spacing(10)
    .into()
}

fn country_option<'a>(
    code: Option<String>,
    name: impl Into<String>,
    hint: impl Into<String>,
    is_selected: bool,
) -> Element<'a, Message> {
    let value = code.clone().unwrap_or_default();
    let body = row![
        widgets::monogram(code.unwrap_or_else(|| "··".into()), Tone::Neutral),
        column![text(name.into()).size(13), widgets::faint(hint.into())]
            .spacing(1)
            .width(Length::Fill),
    ]
    .spacing(10)
    .align_y(Alignment::Center);

    container(
        button(body)
            .width(Length::Fill)
            .padding(Padding::from([6, 8]))
            .style(theme::bare())
            .on_press(Message::EditorCountry(value)),
    )
    .width(Length::Fill)
    .style(theme::connection_card(is_selected))
    .into()
}

fn city_panel<'a>(app: &'a App, editor: &'a ConnectionEditor) -> Element<'a, Message> {
    let Some(country) = editor.country.as_deref() else {
        return column![
            widgets::eyebrow(app.i18n.editor_cities_title()),
            widgets::muted(app.i18n.editor_cities_pick_country()),
        ]
        .spacing(8)
        .into();
    };

    let title = widgets::eyebrow(app.i18n.editor_cities_title_for(app.country_name(country)));

    if !app.cities_loaded_for(country) {
        return column![title, widgets::muted(app.i18n.editor_cities_loading())]
            .spacing(8)
            .into();
    }

    let mut list = column![city_option(
        None,
        app.i18n.editor_any_city(),
        app.i18n.editor_any_city_hint(),
        editor.city.is_none()
    )]
    .spacing(4);

    match &app.shared.state.cities {
        Some(observation) if !observation.value.is_empty() => {
            for city in &observation.value {
                let hint = if city.features.is_empty() {
                    "—".to_string()
                } else {
                    city.features.join(", ")
                };
                list = list.push(city_option(
                    Some(city.name.clone()),
                    &city.name,
                    &hint,
                    editor.city.as_deref() == Some(city.name.as_str()),
                ));
            }
        }
        _ => list = list.push(widgets::faint(app.i18n.editor_cities_empty())),
    }

    column![title, scrollable(list).height(Length::Fill)]
        .spacing(10)
        .into()
}

fn city_option<'a>(
    city: Option<String>,
    name: impl Into<String>,
    hint: impl Into<String>,
    is_selected: bool,
) -> Element<'a, Message> {
    let value = city.clone().unwrap_or_default();
    let body = row![
        column![text(name.into()).size(13), widgets::faint(hint.into())]
            .spacing(1)
            .width(Length::Fill),
    ]
    .spacing(10)
    .align_y(Alignment::Center);

    container(
        button(body)
            .width(Length::Fill)
            .padding(Padding::from([6, 8]))
            .style(theme::bare())
            .on_press(Message::EditorCity(value)),
    )
    .width(Length::Fill)
    .style(theme::connection_card(is_selected))
    .into()
}

#[cfg(test)]
mod tests {
    use protonvpn_core::i18n::{I18n, Locale};

    #[test]
    fn the_editor_reads_in_the_source_language() {
        let i18n = I18n::new(Locale::SOURCE);
        assert_eq!(i18n.editor_title_new(), "New connection");
        assert_eq!(i18n.editor_title_edit(), "Edit connection");
        assert_eq!(i18n.editor_cancel(), "Cancel");
        assert_eq!(i18n.editor_save(), "Save");
        assert_eq!(i18n.editor_any_city_hint(), "the fastest in the country");
    }

    #[test]
    fn the_data_in_a_message_stays_data() {
        let i18n = I18n::new(Locale::SOURCE);
        // The CLI's flag, spelled the way the CLI spells it.
        assert_eq!(i18n.editor_any_country_hint(), "without --country");
        // A country name arrives as the CLI printed it and is substituted unchanged.
        assert_eq!(
            i18n.editor_cities_title_for("Netherlands"),
            "Cities · Netherlands"
        );
        // So does the CLI's own error text.
        assert_eq!(
            i18n.editor_country_error("no such country"),
            "The CLI answered with an error: no such country"
        );
    }

    #[test]
    fn the_editor_is_translated_rather_than_copied() {
        let english = I18n::new(Locale::SOURCE);
        let russian = I18n::new(Locale::from_id("ru").unwrap());
        assert_ne!(russian.editor_save(), english.editor_save());
        assert_ne!(russian.editor_any_city(), english.editor_any_city());
        // Data is the exception: the words around the flag are translated, the flag itself is not.
        assert!(english.editor_any_country_hint().contains("--country"));
        assert!(russian.editor_any_country_hint().contains("--country"));
        assert_ne!(
            russian.editor_any_country_hint(),
            english.editor_any_country_hint()
        );
    }
}
