//! The connection editor — a modal over whichever page is open.
//!
//! What it edits is an intent, not a setting: the checkboxes are exactly the CLI's connect flags
//! (`--p2p`, `--securecore`, `--tor`), the country and city are picked from the two lists the CLI
//! prints, and port forwarding is ours. The preview at the bottom is generated by the launcher
//! itself, so what the user reads is the argv that will actually run.

use iced::widget::{Space, button, checkbox, column, container, row, scrollable, text, text_input};
use iced::{Alignment, Element, Font, Length, Padding, Theme};

use protonvpn_core::launcher::Intent;

use crate::app::{App, ConnectionEditor, EditorFlag, Message};
use crate::theme;
use crate::widgets::{self, Tone};

pub(crate) fn view<'a>(app: &'a App, editor: &'a ConnectionEditor) -> Element<'a, Message> {
    let heading = if editor.editing.is_some() {
        "Изменить соединение"
    } else {
        "Новое соединение"
    };

    let header = row![
        column![
            widgets::eyebrow(heading),
            widgets::muted("страна и город — из protonvpn countries list / cities list"),
        ]
        .spacing(2)
        .width(Length::Fill),
        button(text("×").size(16))
            .padding(Padding::from([2, 8]))
            .style(theme::ghost(theme::TEXT_MUTED, false))
            .on_press(Message::EditorCancel),
    ]
    .align_y(Alignment::Center);

    let name = column![
        text("Название соединения").size(13),
        text_input("например, Работа", &editor.name)
            .on_input(Message::EditorName)
            .padding(Padding::from([9, 12]))
            .width(Length::Fill),
    ]
    .spacing(6);

    let flags = row(EditorFlag::ALL
        .iter()
        .map(|flag| {
            let checked = match flag {
                EditorFlag::P2p => editor.p2p,
                EditorFlag::SecureCore => editor.secure_core,
                EditorFlag::Tor => editor.tor,
                EditorFlag::PortForwarding => editor.port_forwarding,
            };
            checkbox(flag.label(), checked)
                .text_size(13)
                .on_toggle(move |value| Message::EditorFlag(*flag, value))
                .into()
        })
        .collect::<Vec<Element<'_, Message>>>())
    .spacing(18)
    .align_y(Alignment::Center);

    let body = row![
        container(country_panel(app, editor))
            .width(Length::FillPortion(3))
            .height(Length::Fixed(330.0)),
        container(city_panel(app, editor))
            .width(Length::FillPortion(2))
            .height(Length::Fixed(330.0))
            .padding(Padding::from([0, 0])),
    ]
    .spacing(14);

    let preview = container(
        text(format!(
            "$ {}",
            Intent::Connect(editor.target()).argv().join(" ")
        ))
        .size(12)
        .font(Font::MONOSPACE)
        .style(|_: &Theme| iced::widget::text::Style {
            color: Some(theme::TEXT_MUTED),
        }),
    )
    .padding(Padding::from([8, 12]))
    .width(Length::Fill)
    .style(theme::flat_card);

    let buttons = row![
        button(text("Отмена").size(13))
            .padding(Padding::from([8, 16]))
            .style(theme::outlined(theme::BORDER, theme::TEXT))
            .on_press(Message::EditorCancel),
        button(text("Сохранить").size(13))
            .padding(Padding::from([8, 18]))
            .style(theme::filled(theme::ACCENT))
            .on_press(Message::EditorSave),
    ]
    .spacing(8);

    let footer = row![
        preview,
        Space::new(Length::Fixed(12.0), Length::Fixed(1.0)),
        buttons,
    ]
    .align_y(Alignment::Center)
    .width(Length::Fill);

    let modal = container(
        column![header, widgets::separator(), name, flags, body, footer]
            .spacing(14)
            .padding(Padding::from([18, 20])),
    )
    .width(Length::Fixed(760.0))
    .style(theme::card);

    container(modal)
        .padding(Padding::from([28, 28]))
        .width(Length::Fill)
        .height(Length::Fill)
        .center_x(Length::Fill)
        .center_y(Length::Fill)
        .style(theme::backdrop)
        .into()
}

fn country_panel<'a>(app: &'a App, editor: &'a ConnectionEditor) -> Element<'a, Message> {
    let search = text_input("Поиск страны или кода", &editor.country_filter)
        .on_input(Message::EditorFilter)
        .padding(Padding::from([8, 12]));

    let mut list = column![country_option(
        None,
        "Любая страна",
        "без --country",
        editor.country.is_none(),
    )]
    .spacing(4);

    let Some(observation) = &app.shared.state.countries else {
        list = list.push(widgets::note(
            "Список стран ещё не прочитан: `protonvpn countries list` выполняется один раз за \
             запуск.",
        ));
        // The console sits behind this dialog, so if the CLI refused, say so here rather than
        // leaving an empty list and no reason for it.
        if let Some(error) = &app.shared.state.last_error {
            list = list.push(widgets::note(format!(
                "CLI ответил ошибкой: {}",
                error.value.message
            )));
        }
        return column![search, scrollable(list).height(Length::Fill)]
            .spacing(10)
            .into();
    };

    let needle = editor.country_filter.trim().to_lowercase();
    let countries: Vec<&protonvpn_core::model::Country> = observation
        .value
        .iter()
        .filter(|country| {
            needle.is_empty()
                || country.name.to_lowercase().contains(&needle)
                || country.code.to_lowercase().contains(&needle)
        })
        .collect();

    if countries.is_empty() {
        list = list.push(widgets::faint("Ничего не найдено."));
    }
    for country in countries {
        list = list.push(country_option(
            Some(country.code.clone()),
            &country.name,
            &country.code,
            editor.country.as_deref() == Some(country.code.as_str()),
        ));
    }

    column![
        search,
        scrollable(list).height(Length::Fill),
        widgets::faint(app.countries_age().unwrap_or_else(|| "—".into())),
    ]
    .spacing(10)
    .into()
}

fn country_option<'a>(
    code: Option<String>,
    name: impl Into<String>,
    hint: impl Into<String>,
    is_selected: bool,
) -> Element<'a, Message> {
    let value = code.clone().unwrap_or_default();
    let body = row![
        widgets::monogram(code.unwrap_or_else(|| "··".into()), Tone::Neutral),
        column![text(name.into()).size(13), widgets::faint(hint.into())]
            .spacing(1)
            .width(Length::Fill),
    ]
    .spacing(10)
    .align_y(Alignment::Center);

    container(
        button(body)
            .width(Length::Fill)
            .padding(Padding::from([6, 8]))
            .style(theme::bare())
            .on_press(Message::EditorCountry(value)),
    )
    .width(Length::Fill)
    .style(theme::connection_card(is_selected))
    .into()
}

fn city_panel<'a>(app: &'a App, editor: &'a ConnectionEditor) -> Element<'a, Message> {
    let Some(country) = editor.country.as_deref() else {
        return column![
            widgets::eyebrow("Города"),
            widgets::muted("Сначала выберите страну — города запрашиваются для конкретной."),
        ]
        .spacing(8)
        .into();
    };

    let title = widgets::eyebrow(format!("Города · {}", app.country_name(country)));

    if !app.cities_loaded_for(country) {
        return column![title, widgets::muted("Запрашиваю список городов…")]
            .spacing(8)
            .into();
    }

    let mut list = column![city_option(
        None,
        "Любой город",
        "быстрейший в стране",
        editor.city.is_none()
    )]
    .spacing(4);

    match &app.shared.state.cities {
        Some(observation) if !observation.value.is_empty() => {
            for city in &observation.value {
                let hint = if city.features.is_empty() {
                    "—".to_string()
                } else {
                    city.features.join(", ")
                };
                list = list.push(city_option(
                    Some(city.name.clone()),
                    &city.name,
                    &hint,
                    editor.city.as_deref() == Some(city.name.as_str()),
                ));
            }
        }
        _ => list = list.push(widgets::faint("В этой стране нет городов в списке.")),
    }

    column![title, scrollable(list).height(Length::Fill)]
        .spacing(10)
        .into()
}

fn city_option<'a>(
    city: Option<String>,
    name: impl Into<String>,
    hint: impl Into<String>,
    is_selected: bool,
) -> Element<'a, Message> {
    let value = city.clone().unwrap_or_default();
    let body = row![
        column![text(name.into()).size(13), widgets::faint(hint.into())]
            .spacing(1)
            .width(Length::Fill),
    ]
    .spacing(10)
    .align_y(Alignment::Center);

    container(
        button(body)
            .width(Length::Fill)
            .padding(Padding::from([6, 8]))
            .style(theme::bare())
            .on_press(Message::EditorCity(value)),
    )
    .width(Length::Fill)
    .style(theme::connection_card(is_selected))
    .into()
}
