//! The window — an elm-style update loop over the engine's snapshot.
//!
//! Views never call the runner (`docs/architecture.md` §1). Everything they do is a
//! [`Request`] sent to the engine, and everything they show comes from a snapshot plus the log
//! bus. That is what keeps the tray, the window and the interpreter from ever disagreeing about
//! what the CLI said.
//!
//! Three pieces of the contract are easy to lose in a UI and are therefore called out here:
//!
//! * **freshness is an age, never a verdict** (§7) — there is no "stale" badge anywhere below,
//! * **nothing is invented** (§5) — `Unknown` renders as its own words, not as "отключено",
//! * **the only program we run is `protonvpn`** (§0) — a connection profile is a way of spelling
//!   that program's argv, and the preview in the editor is generated by the launcher itself.
//!
//! The window has two shells. Signed out, it is the login page — a decision, not a tab, because
//! there is nothing else to do until `protonvpn info` names an account. Signed in, it is a
//! sidebar with two pages and the console pinned underneath both.

mod views;

use std::collections::HashMap;
use std::sync::Arc;
use std::sync::mpsc::Receiver;
use std::time::{Duration, Instant};

use iced::widget::{operation, scrollable};
use iced::{Element, Subscription, Task};
use iced::{clipboard, exit, time, window};

use protonvpn_core::config::{Config, ConfigStore, SYSTEM_FASTEST, SavedConnection};
use protonvpn_core::engine::{EngineHandle, EngineOptions, Request, Shared, TrayView, UiCommand};
use protonvpn_core::launcher::Intent;
use protonvpn_core::model::{ConnectTarget, InvocationId};

use crate::console::ConsoleModel;
use crate::desktop::{self, Desktop};
use crate::theme;
use crate::tray::{self, TrayCommand};

/// The window redraws on this beat: it is what makes the console feel live and what keeps the
/// "updated N mins ago" line climbing while the user watches. It is not a status poll — the
/// engine's polling policy (§7) is untouched by how often the view repaints.
const TICK: Duration = Duration::from_millis(200);
const CONSOLE_ID: &str = "console-transcript";

pub fn run() -> iced::Result {
    // A **daemon**, not an application, and this is the whole reason: `iced::application` exits
    // when its last window is destroyed, and winit cannot hide a window on Wayland at all
    // ("Not possible on Wayland" in `set_visible`). Closing the window therefore has to mean
    // *destroying* it, and the app has to keep running afterwards — which is what a daemon does.
    iced::daemon(boot, App::update, App::view)
        .title("Proton VPN")
        .subscription(App::subscription)
        .theme(|_state: &App, _window: window::Id| theme::app())
        .run()
}

/// Everything the application comes up with: the config, the entries we keep in step with it, the
/// tray, the engine, and the first window (unless this run is meant to live in the tray).
///
/// iced 0.14 asks for a `Fn` here — the shell may, in principle, boot the program more than once —
/// so nothing is captured from [`run`]. A second call would build a second, self-contained
/// application rather than borrow the first one's engine.
fn boot() -> (App, Task<Message>) {
    let store = ConfigStore::default();
    let (config, config_error) = match store.load() {
        Ok(config) => (config, None),
        Err(error) => (Config::default(), Some(error.to_string())),
    };

    // Keep the autostart entry in step with the config on every start: a user who deletes the
    // file should not be surprised by it coming back unasked, and one who enables it in the app
    // should not have to enable it twice.
    let desktop = Desktop::default();
    let exec = desktop::current_exec();
    let autostart_note = match desktop.sync_autostart(config.autostart, &exec) {
        Ok(_) => None,
        Err(error) => Some(format!("автозапуск: {error}")),
    };

    // The application entry, and the same rule: the config decides, every start re-asserts it.
    // This is the file that gives the window its name and icon (§12) — without it a Wayland
    // compositor has nothing to match the window against.
    let entry_note = match desktop.sync_entry(config.desktop_entry, &exec) {
        Ok(_) => None,
        Err(error) => Some(format!("ярлык: {error}")),
    };

    let start_minimized = config.start_minimized;
    // "Connect at startup" connects the *selected connection*, because that is the only thing the
    // app has that means "what should `protonvpn connect` be".
    let startup_connect = config.connect_at_startup.then(|| selected_target(&config));

    // The tray comes first, because whether there *is* one decides whether a start-to-tray run is
    // possible at all: hiding into nothing is exactly what §9 forbids.
    let (tray_commands, tray_rx) = std::sync::mpsc::channel::<TrayCommand>();
    let initial_view = TrayView {
        status: protonvpn_core::model::ConnectionStatus::Unknown,
        detail: None,
        age_text: "updated just now".into(),
    };
    let tray = tray::spawn(tray_commands, initial_view);
    let tray_available = tray.is_some();
    let presenter = tray.map(Arc::new);

    // The window's app id is ours, and must never be `proton.vpn.app.gtk`: the CLI refuses to run
    // while that name is on the session bus (`docs/cli-surface.md` §2). It is also what lets the
    // desktop match the window to packaging/protonvpn-gui.desktop.
    let window_settings = window::Settings {
        size: iced::Size::new(1180.0, 820.0),
        min_size: Some(iced::Size::new(880.0, 560.0)),
        exit_on_close_request: false,
        platform_specific: window::settings::PlatformSpecific {
            application_id: desktop::APP_ID.to_string(),
            ..Default::default()
        },
        ..Default::default()
    };
    let start_in_tray = start_minimized && tray_available;

    let mut options = EngineOptions::new(store, config.clone());
    options.tray_available = tray_available;
    options.tray = presenter.as_ref().map(|presenter| {
        Box::new(SharedPresenter(Arc::clone(presenter)))
            as Box<dyn protonvpn_core::engine::TrayPresenter>
    });
    let engine = protonvpn_core::engine::spawn(options);

    let mut app = App::new(engine, config, tray_rx, presenter, window_settings);
    app.tray_available = tray_available;
    app.notice = config_error.or(autostart_note).or(entry_note);

    // No window at all when the app is meant to start in the tray: "the app is in the tray
    // and connected to the configured country, no window" is an exit criterion.
    let open = if start_in_tray {
        Task::none()
    } else {
        let (id, open) = window::open(app.window_settings.clone());
        app.window = Some(id);
        open.map(Message::WindowOpened)
    };

    let task = Task::batch([
        open,
        match startup_connect {
            Some(target) => Task::done(Message::StartupConnect(target)),
            None => Task::none(),
        },
    ]);
    (app, task)
}

/// Adapter so the tray handle can be shared with the engine and still be shut down by the app.
struct SharedPresenter(Arc<tray::TrayPresenter>);

impl protonvpn_core::engine::TrayPresenter for SharedPresenter {
    fn update(&self, view: TrayView) {
        self.0.update(view);
    }
}

/// The window's pages. Two, because there are two jobs: "is it working" and "make it work".
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Page {
    Overview,
    Settings,
}

impl Page {
    pub const ALL: [Page; 2] = [Page::Overview, Page::Settings];

    fn label(self) -> &'static str {
        match self {
            Self::Overview => "Обзор",
            Self::Settings => "Настройки",
        }
    }
}

/// The settings page's sections. Every one of them holds settings that exist: nothing here is a
/// placeholder for a feature the CLI does not have (`docs/architecture.md` §11).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SettingsTab {
    General,
    Connection,
    Polling,
    Account,
}

impl SettingsTab {
    pub const ALL: [SettingsTab; 4] = [
        SettingsTab::General,
        SettingsTab::Connection,
        SettingsTab::Polling,
        SettingsTab::Account,
    ];

    fn label(self) -> &'static str {
        match self {
            Self::General => "Общие",
            Self::Connection => "Подключение",
            Self::Polling => "Опрос",
            Self::Account => "Аккаунт",
        }
    }
}

/// The CLI's own three shortcuts. They are presets, not profiles: they carry no name, no country
/// and nothing editable, and they exist because `--p2p` and `--securecore` are real flags.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SystemPreset {
    Fastest,
    SecureCore,
    P2p,
}

impl SystemPreset {
    pub const ALL: [SystemPreset; 3] = [
        SystemPreset::Fastest,
        SystemPreset::SecureCore,
        SystemPreset::P2p,
    ];

    pub fn id(self) -> &'static str {
        match self {
            Self::Fastest => protonvpn_core::config::SYSTEM_FASTEST,
            Self::SecureCore => protonvpn_core::config::SYSTEM_SECURE_CORE,
            Self::P2p => protonvpn_core::config::SYSTEM_P2P,
        }
    }

    pub fn from_id(id: &str) -> Option<Self> {
        Self::ALL.into_iter().find(|preset| preset.id() == id)
    }

    pub fn name(self) -> &'static str {
        match self {
            Self::Fastest => "Fastest",
            Self::SecureCore => "Secure Core",
            Self::P2p => "P2P",
        }
    }

    pub fn summary(self) -> &'static str {
        match self {
            Self::Fastest => "Быстрейший сервер",
            Self::SecureCore => "Двойной маршрут",
            Self::P2p => "Серверы для P2P",
        }
    }

    pub fn monogram(self) -> &'static str {
        match self {
            Self::Fastest => "F",
            Self::SecureCore => "SC",
            Self::P2p => "P2P",
        }
    }

    pub fn badges(self) -> &'static [&'static str] {
        match self {
            Self::Fastest => &[],
            Self::SecureCore => &["SECURE CORE"],
            Self::P2p => &["P2P", "ПОРТ"],
        }
    }

    pub fn target(self) -> ConnectTarget {
        match self {
            Self::Fastest => ConnectTarget::fastest(),
            Self::SecureCore => ConnectTarget {
                secure_core: true,
                ..Default::default()
            },
            Self::P2p => ConnectTarget {
                p2p: true,
                // A preset named after P2P is the one place a port mapping is meaningful: the CLI
                // only offers one on P2P-capable servers (`docs/cli-surface.md` §1).
                port_forwarding: true,
                ..Default::default()
            },
        }
    }
}

/// The target the selection stands for. An id that no longer resolves — a profile deleted in
/// another window, a hand-edited config — falls back to `connect`, and says so by being `Fastest`
/// rather than by pretending.
pub fn selected_target(config: &Config) -> ConnectTarget {
    match config.selected_connection.as_deref() {
        Some(id) => match SystemPreset::from_id(id) {
            Some(preset) => preset.target(),
            None => config
                .connection(id)
                .map(SavedConnection::target)
                .unwrap_or_else(ConnectTarget::fastest),
        },
        None => ConnectTarget::fastest(),
    }
}

/// Our own switches, as opposed to the CLI's settings.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AppToggle {
    ConnectAtStartup,
    StartMinimized,
    Autostart,
    DesktopEntry,
    Probe,
}

/// The four checkboxes of the connection editor. Country and city are picked in the lists.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EditorFlag {
    P2p,
    SecureCore,
    Tor,
    PortForwarding,
}

impl EditorFlag {
    pub const ALL: [EditorFlag; 4] = [
        EditorFlag::P2p,
        EditorFlag::SecureCore,
        EditorFlag::Tor,
        EditorFlag::PortForwarding,
    ];

    pub fn label(self) -> &'static str {
        match self {
            Self::P2p => "P2P",
            Self::SecureCore => "Secure Core",
            Self::Tor => "TOR",
            Self::PortForwarding => "Порт-форвардинг",
        }
    }
}

/// The state of the "new / edit connection" modal. Held by the app rather than by the view so a
/// repaint cannot lose what the user typed.
#[derive(Debug, Clone)]
pub struct ConnectionEditor {
    /// `Some(id)` when an existing profile is being changed; the id survives a rename.
    pub editing: Option<String>,
    pub name: String,
    pub country: Option<String>,
    pub city: Option<String>,
    pub p2p: bool,
    pub secure_core: bool,
    pub tor: bool,
    pub port_forwarding: bool,
    pub country_filter: String,
}

impl ConnectionEditor {
    fn new() -> Self {
        Self {
            editing: None,
            name: String::new(),
            country: None,
            city: None,
            p2p: false,
            secure_core: false,
            tor: false,
            port_forwarding: false,
            country_filter: String::new(),
        }
    }

    fn from_saved(saved: &SavedConnection) -> Self {
        Self {
            editing: Some(saved.id.clone()),
            name: saved.name.clone(),
            country: saved.country.clone(),
            city: saved.city.clone(),
            p2p: saved.p2p,
            secure_core: saved.secure_core,
            tor: saved.tor,
            port_forwarding: saved.port_forwarding,
            country_filter: String::new(),
        }
    }

    fn target(&self) -> ConnectTarget {
        ConnectTarget {
            country: self.country.clone(),
            city: self.city.clone(),
            server: None,
            p2p: self.p2p,
            secure_core: self.secure_core,
            tor: self.tor,
            random: false,
            port_forwarding: self.port_forwarding,
        }
    }

    fn into_saved(self) -> SavedConnection {
        SavedConnection {
            id: self.editing.unwrap_or_default(),
            name: self.name.trim().to_string(),
            country: self.country,
            city: self.city,
            p2p: self.p2p,
            secure_core: self.secure_core,
            tor: self.tor,
            port_forwarding: self.port_forwarding,
        }
    }
}

#[derive(Debug, Clone)]
pub enum Message {
    Tick,
    StartupConnect(ConnectTarget),
    CloseRequested(window::Id),
    WindowOpened(window::Id),
    WindowClosed(window::Id),
    ShowWindow,
    HideWindow,
    Quit,
    PageSelected(Page),
    SettingsTabSelected(SettingsTab),
    ToggleConsole,
    ConsoleScrolled(scrollable::Viewport),
    ScrollToBottom,
    CopyAll,
    CopyInvocation(InvocationId),
    RefreshStatus,
    RefreshSettings,
    CancelRun,
    Probe,
    /// Connect the selected connection, or disconnect when something is connected.
    PrimaryAction,
    ConnectionSelected(String),
    ConnectionNew,
    ConnectionEdit(String),
    ConnectionDelete(String),
    SelectedPortForwarding(bool),
    EditorName(String),
    EditorCountry(String),
    EditorCity(String),
    EditorFlag(EditorFlag, bool),
    EditorFilter(String),
    EditorSave,
    EditorCancel,
    SettingChoice {
        key: String,
        value: String,
    },
    SettingDraft {
        key: String,
        value: String,
    },
    SettingApply {
        key: String,
    },
    Toggle(AppToggle, bool),
    DnsChanged(String),
    /// The user asked to sign in, whatever the interpreter currently believes about the account.
    SignInRequested,
    SignInCancelled,
    LoginUsername(String),
    LoginPassword(String),
    LoginTwoFactor(String),
    LoginShowPassword(bool),
    LoginSubmit,
    LoginTwoFactorSubmit,
    Logout,
    ManualInput(String),
    ManualSend,
    PortRefresh,
    PortRelease,
    CopyPort,
    DismissNotice,
}

pub struct App {
    engine: EngineHandle,
    config: Config,
    shared: Shared,
    console: ConsoleModel,
    tray_commands: Receiver<TrayCommand>,
    tray: Option<Arc<tray::TrayPresenter>>,
    /// The entries we keep in step with the config. Held rather than rebuilt per call so that the
    /// settings page can ask about them without reading the XDG environment on every frame.
    desktop: Desktop,
    tray_available: bool,
    window: Option<window::Id>,
    window_settings: window::Settings,
    page: Page,
    settings_tab: SettingsTab,
    editor: Option<ConnectionEditor>,
    console_expanded: bool,
    stick_to_bottom: bool,
    dns_servers: String,
    setting_drafts: HashMap<String, String>,
    /// The user opened the sign-in page themselves. The login gate is normally
    /// [`App::signed_out`], which is a claim *about the CLI*; this is the escape hatch for the
    /// case where that claim is wrong or unknown — a parser that misses a new spelling must not
    /// be able to lock somebody out of their own app.
    force_login: bool,
    login_username: String,
    login_password: String,
    login_two_factor: String,
    login_show_password: bool,
    manual_input: String,
    notice: Option<String>,
    copied_port_at: Option<Instant>,
}

impl App {
    fn new(
        engine: EngineHandle,
        config: Config,
        tray_commands: Receiver<TrayCommand>,
        tray: Option<Arc<tray::TrayPresenter>>,
        window_settings: window::Settings,
    ) -> Self {
        let shared = engine.snapshot();
        let mut console = ConsoleModel::default();
        console.refresh(&engine.bus().lock().unwrap_or_else(|p| p.into_inner()));
        Self {
            engine,
            config,
            shared,
            console,
            tray_commands,
            tray,
            desktop: Desktop::default(),
            tray_available: false,
            window: None,
            window_settings,
            page: Page::Overview,
            settings_tab: SettingsTab::General,
            editor: None,
            console_expanded: false,
            stick_to_bottom: true,
            dns_servers: String::new(),
            setting_drafts: HashMap::new(),
            force_login: false,
            login_username: String::new(),
            login_password: String::new(),
            login_two_factor: String::new(),
            login_show_password: false,
            manual_input: String::new(),
            notice: None,
            copied_port_at: None,
        }
    }

    fn subscription(&self) -> Subscription<Message> {
        Subscription::batch([
            time::every(TICK).map(|_| Message::Tick),
            window::close_requests().map(Message::CloseRequested),
            // A destroyed window must be forgotten, or the tray's "Открыть окно" would try to
            // focus something that no longer exists.
            window::close_events().map(Message::WindowClosed),
        ])
    }

    fn update(&mut self, message: Message) -> Task<Message> {
        match message {
            Message::Tick => self.tick(),
            Message::StartupConnect(target) => {
                self.engine.send(Request::Run(Intent::Connect(target)));
                Task::none()
            }
            Message::CloseRequested(id) => {
                if self.tray_available {
                    // Closing returns to the tray, which is the point of the app existing without
                    // a window. With no tray, hiding would hide it into nothing, so we say why
                    // instead (§9).
                    self.window = None;
                    return window::close(id);
                }
                self.notice = Some(
                    "Трея нет, скрывать окно некуда. Закрыть приложение — кнопка «Выход».".into(),
                );
                Task::none()
            }
            Message::WindowOpened(id) => {
                // The window the tray asked for exists now; remember it so the next click just
                // focuses it instead of opening another one.
                self.window = Some(id);
                Task::none()
            }
            Message::WindowClosed(id) => {
                if self.window == Some(id) {
                    self.window = None;
                }
                Task::none()
            }
            Message::ShowWindow => {
                self.engine.send(Request::Attention);
                match self.window {
                    Some(id) => Task::batch([
                        window::set_mode(id, window::Mode::Windowed),
                        window::gain_focus(id),
                    ]),
                    None => {
                        // The window was destroyed on close; the tray brings a fresh one back.
                        // The daemon opened nothing by itself, so there is exactly one at a time.
                        let (id, open) = window::open(self.window_settings.clone());
                        self.window = Some(id);
                        Task::batch([open.map(Message::WindowOpened)])
                    }
                }
            }
            Message::HideWindow => match (self.window, self.tray_available) {
                (Some(id), true) => {
                    self.window = None;
                    window::close(id)
                }
                _ => {
                    self.notice = Some("Трея нет — окно остаётся открытым.".into());
                    Task::none()
                }
            },
            Message::Quit => {
                if let Some(tray) = &self.tray {
                    tray.shutdown();
                }
                // Give the engine a moment to hand the forwarded port back before the process
                // goes away; a stale mapping outliving the app is exactly the misinformation
                // §10.1 warns about.
                self.engine.shutdown(Duration::from_millis(1500));
                exit()
            }
            Message::PageSelected(page) => {
                self.page = page;
                if page == Page::Settings {
                    self.ensure_settings();
                }
                Task::none()
            }
            Message::SettingsTabSelected(tab) => {
                self.settings_tab = tab;
                self.ensure_settings();
                Task::none()
            }
            Message::ToggleConsole => {
                self.console_expanded = !self.console_expanded;
                if self.console_expanded {
                    self.stick_to_bottom = true;
                    return self.scroll_to_bottom();
                }
                Task::none()
            }
            Message::PrimaryAction => {
                if self.shared.state.connection.value.is_connected() {
                    self.engine.send(Request::Run(Intent::Disconnect));
                } else {
                    self.engine
                        .send(Request::Run(Intent::Connect(selected_target(&self.config))));
                }
                Task::none()
            }
            Message::ConnectionSelected(id) => {
                let mut config = self.config.clone();
                config.selected_connection = Some(id);
                self.save_config(config);
                Task::none()
            }
            Message::ConnectionNew => {
                self.editor = Some(ConnectionEditor::new());
                self.ensure_countries();
                Task::none()
            }
            Message::ConnectionEdit(id) => {
                if let Some(saved) = self.config.connection(&id).cloned() {
                    if let Some(country) = &saved.country {
                        self.ensure_cities(country);
                    }
                    self.editor = Some(ConnectionEditor::from_saved(&saved));
                }
                self.ensure_countries();
                Task::none()
            }
            Message::ConnectionDelete(id) => {
                let mut config = self.config.clone();
                config.connections.retain(|saved| saved.id != id);
                if config.selected_connection.as_deref() == Some(id.as_str()) {
                    config.selected_connection = Some(SYSTEM_FASTEST.to_string());
                }
                self.save_config(config);
                Task::none()
            }
            Message::SelectedPortForwarding(value) => {
                let Some(id) = self.config.selected_connection.clone() else {
                    return Task::none();
                };
                let mut config = self.config.clone();
                if let Some(saved) = config.connection_mut(&id) {
                    saved.port_forwarding = value;
                }
                self.save_config(config);
                Task::none()
            }
            Message::EditorName(value) => {
                if let Some(editor) = &mut self.editor {
                    editor.name = value;
                }
                Task::none()
            }
            Message::EditorCountry(code) => {
                if let Some(editor) = &mut self.editor {
                    let country = (!code.is_empty()).then_some(code);
                    // The city list belongs to the country, so changing the country drops the
                    // city rather than silently carrying a city from another country.
                    if editor.country != country {
                        editor.city = None;
                    }
                    editor.country = country;
                    if let Some(country) = editor.country.clone() {
                        self.ensure_cities(&country);
                    }
                }
                Task::none()
            }
            Message::EditorCity(city) => {
                if let Some(editor) = &mut self.editor {
                    editor.city = (!city.is_empty()).then_some(city);
                }
                Task::none()
            }
            Message::EditorFlag(flag, value) => {
                if let Some(editor) = &mut self.editor {
                    match flag {
                        EditorFlag::P2p => editor.p2p = value,
                        EditorFlag::SecureCore => editor.secure_core = value,
                        EditorFlag::Tor => editor.tor = value,
                        EditorFlag::PortForwarding => editor.port_forwarding = value,
                    }
                }
                Task::none()
            }
            Message::EditorFilter(value) => {
                if let Some(editor) = &mut self.editor {
                    editor.country_filter = value;
                }
                Task::none()
            }
            Message::EditorCancel => {
                self.editor = None;
                Task::none()
            }
            Message::EditorSave => {
                let Some(editor) = self.editor.clone() else {
                    return Task::none();
                };
                if editor.name.trim().is_empty() {
                    self.notice = Some("У соединения должно быть имя.".into());
                    return Task::none();
                }
                let editing = editor.editing.clone();
                let saved = editor.into_saved();
                let mut config = self.config.clone();
                match editing {
                    Some(id) => {
                        if let Some(existing) = config.connection_mut(&id) {
                            *existing = saved;
                        }
                    }
                    None => {
                        let id = config.add_connection(saved);
                        config.selected_connection = Some(id);
                    }
                }
                self.editor = None;
                self.save_config(config);
                Task::none()
            }
            Message::RefreshStatus => {
                self.engine.send(Request::Run(Intent::RefreshStatus));
                Task::none()
            }
            Message::CancelRun => {
                self.engine.send(Request::Cancel);
                Task::none()
            }
            Message::RefreshSettings => {
                self.engine.send(Request::Run(Intent::ListSettings));
                Task::none()
            }
            Message::Probe => {
                self.engine.send(Request::Probe);
                Task::none()
            }
            Message::SettingChoice { key, value } => {
                self.apply_setting(key, value);
                Task::none()
            }
            Message::SettingDraft { key, value } => {
                self.setting_drafts.insert(key, value);
                Task::none()
            }
            Message::SettingApply { key } => {
                let value = self.setting_drafts.remove(&key).unwrap_or_default();
                if value.trim().is_empty() {
                    self.notice = Some("Значение не может быть пустым.".into());
                    return Task::none();
                }
                self.apply_setting(key, value.trim().to_string());
                Task::none()
            }
            Message::DnsChanged(value) => {
                self.dns_servers = value;
                Task::none()
            }
            Message::Toggle(which, value) => {
                self.toggle(which, value);
                Task::none()
            }
            Message::SignInRequested => {
                self.force_login = true;
                if self.shared.state.account.is_none() {
                    self.engine.send(Request::Run(Intent::AccountInfo));
                }
                Task::none()
            }
            Message::SignInCancelled => {
                self.force_login = false;
                Task::none()
            }
            Message::LoginUsername(value) => {
                self.login_username = value;
                Task::none()
            }
            Message::LoginPassword(value) => {
                self.login_password = value;
                Task::none()
            }
            Message::LoginTwoFactor(value) => {
                self.login_two_factor = value;
                Task::none()
            }
            Message::LoginShowPassword(show) => {
                self.login_show_password = show;
                Task::none()
            }
            Message::LoginSubmit => {
                let username = self.login_username.trim().to_string();
                if username.is_empty() || self.login_password.is_empty() {
                    self.notice = Some("Нужны имя пользователя и пароль.".into());
                    return Task::none();
                }
                self.engine.send(Request::SignIn {
                    username,
                    password: self.login_password.clone(),
                    two_factor: None,
                });
                // The password does not linger in the window state either.
                self.login_password.clear();
                Task::none()
            }
            Message::LoginTwoFactorSubmit => {
                let code = self.login_two_factor.trim().to_string();
                if code.is_empty() {
                    self.notice = Some("Введите код из приложения-аутентификатора.".into());
                    return Task::none();
                }
                self.engine.send(Request::Stdin { text: code });
                self.login_two_factor.clear();
                Task::none()
            }
            Message::Logout => {
                self.engine.send(Request::Run(Intent::SignOut));
                Task::none()
            }
            Message::ManualInput(value) => {
                self.manual_input = value;
                Task::none()
            }
            Message::ManualSend => {
                let text = std::mem::take(&mut self.manual_input);
                if !text.is_empty() {
                    self.engine.send(Request::Stdin { text });
                }
                Task::none()
            }
            Message::PortRefresh => {
                self.engine.send(Request::PortForwardRefresh);
                Task::none()
            }
            Message::PortRelease => {
                self.engine.send(Request::ReleasePort);
                Task::none()
            }
            Message::CopyPort => match self.shared.state.port_forwarding.value.port() {
                Some(port) => {
                    self.copied_port_at = Some(Instant::now());
                    clipboard::write(port.to_string())
                }
                None => Task::none(),
            },
            Message::CopyInvocation(id) => {
                let text = self
                    .console
                    .blocks
                    .iter()
                    .find(|block| block.id == id)
                    .map(|block| block.transcript.clone());
                match text {
                    Some(text) => clipboard::write(text),
                    None => Task::none(),
                }
            }
            Message::CopyAll => clipboard::write(self.console.transcript.clone()),
            Message::ConsoleScrolled(viewport) => {
                // "Stick to bottom" while the user is at the bottom; stop as soon as they scroll
                // up, because fighting a reader for the scroll position is the classic way to make
                // a live log unusable.
                let at_bottom = viewport.relative_offset().y >= 0.995;
                self.stick_to_bottom = at_bottom;
                Task::none()
            }
            Message::ScrollToBottom => {
                self.stick_to_bottom = true;
                self.scroll_to_bottom()
            }
            Message::DismissNotice => {
                self.notice = None;
                Task::none()
            }
        }
    }

    /// One beat: take whatever the tray and the engine have produced, and repaint.
    fn tick(&mut self) -> Task<Message> {
        let mut tasks: Vec<Task<Message>> = Vec::new();

        while let Ok(command) = self.tray_commands.try_recv() {
            match command {
                TrayCommand::Show => tasks.push(Task::done(Message::ShowWindow)),
                TrayCommand::Quit => tasks.push(Task::done(Message::Quit)),
                TrayCommand::Connect => self
                    .engine
                    .send(Request::Run(Intent::Connect(selected_target(&self.config)))),
                TrayCommand::Disconnect => self.engine.send(Request::Run(Intent::Disconnect)),
            }
        }

        let console_before = self.console.version();
        let shared = self.engine.snapshot();
        let prompt_changed = shared.pending_prompt != self.shared.pending_prompt;
        self.shared = shared;

        for command in self.engine.take_ui_commands() {
            match command {
                UiCommand::ShowWindow => tasks.push(Task::done(Message::ShowWindow)),
                UiCommand::HideWindow => tasks.push(Task::done(Message::HideWindow)),
                UiCommand::ToggleWindow => tasks.push(Task::done(Message::ToggleConsole)),
                UiCommand::Quit => tasks.push(Task::done(Message::Quit)),
            }
        }

        {
            let bus = self.engine.bus();
            let bus = bus.lock().unwrap_or_else(|poisoned| poisoned.into_inner());
            self.console.refresh(&bus);
        }

        if prompt_changed {
            self.manual_input.clear();
            self.login_two_factor.clear();
        }

        // The escape hatch closes itself as soon as the CLI names an account, so a successful
        // sign-in lands on the app rather than staying on the form.
        if self.force_login && self.account_name().is_some() {
            self.force_login = false;
        }

        if self.console_expanded && self.stick_to_bottom && self.console.version() != console_before
        {
            tasks.push(self.scroll_to_bottom());
        }

        if tasks.is_empty() {
            Task::none()
        } else {
            Task::batch(tasks)
        }
    }

    fn scroll_to_bottom(&self) -> Task<Message> {
        operation::snap_to_end(CONSOLE_ID)
    }

    /// The first time a settings surface is opened, ask the CLI for `config list`. The CLI costs
    /// about a second per invocation, so nothing is fetched until it is wanted.
    fn ensure_settings(&mut self) {
        if self.shared.state.settings.is_none() {
            self.engine.send(Request::Run(Intent::ListSettings));
        }
        if self.shared.state.account.is_none() {
            self.engine.send(Request::Run(Intent::AccountInfo));
        }
    }

    fn ensure_countries(&mut self) {
        if self.shared.state.countries.is_none() {
            self.engine.send(Request::Run(Intent::ListCountries));
        }
    }

    /// The city list belongs to a country; asking for the same one twice is one wasted second.
    fn ensure_cities(&mut self, country: &str) {
        if !self.cities_loaded_for(country) {
            self.engine.send(Request::Run(Intent::ListCities {
                country: country.to_string(),
            }));
        }
    }

    fn apply_setting(&mut self, key: String, value: String) {
        let dns = (key == "custom-dns" && value == "on").then(|| self.dns_servers.clone());
        if let Some(dns) = &dns
            && dns.trim().is_empty()
        {
            self.notice =
                Some("Для custom-dns on укажите серверы: без них CLI отклонит команду.".into());
            return;
        }
        self.engine
            .send(Request::Run(Intent::SetSetting { key, value, dns }));
    }

    fn toggle(&mut self, which: AppToggle, value: bool) {
        match which {
            AppToggle::Probe => {
                let mut config = self.config.clone();
                config.probe_enabled = value;
                self.save_config(config);
            }
            AppToggle::ConnectAtStartup => {
                let mut config = self.config.clone();
                config.connect_at_startup = value;
                self.save_config(config);
            }
            AppToggle::StartMinimized => {
                let mut config = self.config.clone();
                config.start_minimized = value;
                self.save_config(config);
            }
            AppToggle::Autostart => {
                let mut config = self.config.clone();
                config.autostart = value;
                match self.desktop.sync_autostart(value, &desktop::current_exec()) {
                    Ok(_) => self.save_config(config),
                    Err(error) => self.notice = Some(format!("автозапуск: {error}")),
                }
            }
            AppToggle::DesktopEntry => {
                let mut config = self.config.clone();
                config.desktop_entry = value;
                match self.desktop.sync_entry(value, &desktop::current_exec()) {
                    Ok(_) => self.save_config(config),
                    Err(error) => self.notice = Some(format!("ярлык: {error}")),
                }
            }
        }
    }

    fn save_config(&mut self, config: Config) {
        self.config = config.clone();
        self.engine.send(Request::SaveConfig(Box::new(config)));
    }

    fn setting_draft<'a>(&'a self, key: &str) -> &'a str {
        self.setting_drafts
            .get(key)
            .map(String::as_str)
            .unwrap_or("")
    }

    /// Signed out *and known to be*: `protonvpn info` answered and named nobody. Before that
    /// answer, the account is unknown, which is not the same thing as "logged out" (§5).
    pub fn signed_out(&self) -> bool {
        matches!(
            &self.shared.state.account,
            Some(observation) if observation.value.name.is_none()
        )
    }

    /// Whether the sign-in page is up because the user asked for it, rather than because the CLI
    /// said nobody is signed in. The form offers a way back only in that case.
    pub fn login_was_forced(&self) -> bool {
        self.force_login && !self.signed_out()
    }

    pub fn account_name(&self) -> Option<&str> {
        self.shared
            .state
            .account
            .as_ref()
            .and_then(|observation| observation.value.name.as_deref())
    }

    pub fn account_age(&self) -> Option<String> {
        self.shared
            .state
            .account
            .as_ref()
            .map(|observation| observation.age_text())
    }

    /// Which connection is selected, as the name a person would use.
    pub fn selected_name(&self) -> String {
        match self.config.selected_connection.as_deref() {
            Some(id) => match SystemPreset::from_id(id) {
                Some(preset) => preset.name().to_string(),
                None => self
                    .config
                    .connection(id)
                    .map(|saved| saved.name.clone())
                    .unwrap_or_else(|| SystemPreset::Fastest.name().to_string()),
            },
            None => SystemPreset::Fastest.name().to_string(),
        }
    }

    /// Whether the selected connection asks us to hold a lease. `None` when it is not ours to
    /// decide — a system preset that is not P2P cannot be asked for anything.
    pub fn selected_port_forwarding(&self) -> bool {
        match self.config.selected_connection.as_deref() {
            Some(id) => match SystemPreset::from_id(id) {
                Some(preset) => matches!(preset, SystemPreset::P2p),
                None => self
                    .config
                    .connection(id)
                    .is_some_and(|saved| saved.port_forwarding),
            },
            None => false,
        }
    }

    /// The selected profile, when it is one the user can edit.
    pub fn selected_saved(&self) -> Option<&SavedConnection> {
        self.config.selected()
    }

    /// The one-line summary of a profile, with the country's real name when the CLI's list has
    /// been read. Falls back to the code, which is what we know for sure.
    pub fn summary_for(&self, saved: &SavedConnection) -> String {
        let country = saved.country.as_deref().map(|code| self.country_name(code));
        match (country, &saved.city) {
            (Some(country), Some(city)) => format!("{country} · {city}"),
            (Some(country), None) => format!("{country} · любой город"),
            (None, _) => "Любая страна".to_string(),
        }
    }

    /// The country name for a code, when the CLI's list has been read. Falls back to the code,
    /// because the code is what we know for sure.
    pub fn country_name(&self, code: &str) -> String {
        self.shared
            .state
            .countries
            .as_ref()
            .and_then(|observation| {
                observation
                    .value
                    .iter()
                    .find(|country| country.code == code)
                    .map(|country| country.name.clone())
            })
            .unwrap_or_else(|| code.to_string())
    }

    pub fn countries_age(&self) -> Option<String> {
        self.shared
            .state
            .countries
            .as_ref()
            .map(|observation| observation.age_text())
    }

    /// Is the loaded city list the one for this country?
    ///
    /// `cities list <CC>` prints the country's *full name* in its header ("Cities in
    /// Switzerland"), and the interpreter keeps that — so the check has to accept either spelling
    /// or the editor would re-request the same list forever.
    pub fn cities_loaded_for(&self, code: &str) -> bool {
        let Some(loaded) = self.shared.state.cities_country.as_deref() else {
            return false;
        };
        loaded.eq_ignore_ascii_case(code) || loaded.eq_ignore_ascii_case(&self.country_name(code))
    }

    // --- views ------------------------------------------------------------------------------

    fn view(&self, _window: window::Id) -> Element<'_, Message> {
        let content = if self.signed_out() || self.force_login {
            views::login::view(self)
        } else {
            self.shell()
        };

        // The editor is a modal: the page stays visible and dimmed underneath, so the user can
        // still see which connection they are editing.
        let content: Element<'_, Message> = match &self.editor {
            Some(editor) => iced::widget::stack![content, views::editor::view(self, editor)].into(),
            None => content,
        };

        match &self.notice {
            Some(notice) => views::notice_bar(notice, content),
            None => content,
        }
    }

    fn shell(&self) -> Element<'_, Message> {
        let body = match self.page {
            Page::Overview => views::overview::view(self),
            Page::Settings => views::settings::view(self),
        };

        iced::widget::column![
            iced::widget::row![
                views::sidebar(self),
                iced::widget::container(body)
                    .padding(iced::Padding::from([18, 22]))
                    .width(iced::Length::Fill)
                    .height(iced::Length::Fill),
            ]
            .width(iced::Length::Fill)
            .height(iced::Length::Fill),
            views::console::view(self),
        ]
        .width(iced::Length::Fill)
        .height(iced::Length::Fill)
        .into()
    }
}

/// The CLI's settings and the values it accepts.
///
/// Captured from `protonvpn config set <key> --help` on 1.0.3 rather than guessed. `None` means
/// the CLI's value set is open-ended, and the UI offers a text field instead of inventing options.
pub fn setting_values(key: &str) -> Option<&'static [&'static str]> {
    match key {
        "netshield" => Some(&["off", "malware-only", "malware-ads-trackers"]),
        "kill-switch" => Some(&["off", "standard"]),
        "port-forwarding"
        | "custom-dns"
        | "vpn-accelerator"
        | "moderate-nat"
        | "ipv6"
        | "anonymous-crash-reports" => Some(&["off", "on"]),
        _ => None,
    }
}

/// What a CLI setting is called, in words a person reads. `None` for a key we have never seen:
/// the settings tab still shows it, under its own name, rather than hiding it.
pub fn setting_label(key: &str) -> Option<(&'static str, &'static str)> {
    Some(match key {
        "netshield" => (
            "NetShield",
            "Блокировать вредоносные домены на уровне DNS шлюза.",
        ),
        "kill-switch" => ("Kill switch", "Блокировать трафик, если туннель падает."),
        "port-forwarding" => (
            "Порт-форвардинг",
            "Разрешить серверу выдавать проброшенный порт. Аренду держим мы, через NAT-PMP.",
        ),
        "custom-dns" => (
            "Свои DNS",
            "Использовать указанные DNS-серверы внутри туннеля.",
        ),
        "vpn-accelerator" => ("VPN Accelerator", "Ускорение на дальних серверах."),
        "moderate-nat" => ("Moderate NAT", "Мягкий NAT для игр и P2P."),
        "ipv6" => ("IPv6", "Пропускать IPv6 внутри туннеля."),
        "anonymous-crash-reports" => (
            "Анонимные отчёты о сбоях",
            "Отправлять краш-логи без привязки к аккаунту.",
        ),
        _ => return None,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_cli_setting_choices_are_the_ones_the_cli_documents() {
        assert_eq!(
            setting_values("netshield"),
            Some(&["off", "malware-only", "malware-ads-trackers"][..])
        );
        assert_eq!(
            setting_values("kill-switch"),
            Some(&["off", "standard"][..])
        );
        assert_eq!(setting_values("ipv6"), Some(&["off", "on"][..]));
        // An unknown key offers no invented options.
        assert_eq!(setting_values("something-new"), None);
    }

    #[test]
    fn every_setting_we_label_is_one_the_cli_actually_has() {
        // The list is `protonvpn config list` on 1.0.3 (`docs/cli-surface.md` §1). If the CLI
        // grows a key we do not know, it still shows up — under its own name.
        for key in [
            "netshield",
            "kill-switch",
            "port-forwarding",
            "custom-dns",
            "vpn-accelerator",
            "moderate-nat",
            "ipv6",
            "anonymous-crash-reports",
        ] {
            assert!(setting_label(key).is_some(), "{key}");
            assert!(setting_values(key).is_some(), "{key}");
        }
        assert!(setting_label("split-tunneling").is_none());
        assert!(setting_label("auto-connect").is_none());
    }

    /// The bug this pins: the account gate is a claim about what the CLI said, and when that
    /// claim is wrong or unknown the user must still be able to reach the sign-in form. Measured
    /// against the real CLI on 2026-10-01, `protonvpn info` logged out prints `Account: 'None'`,
    /// which used to read as a user called "None" — the login page never appeared and there was
    /// no way to sign in.
    #[test]
    fn the_sign_in_form_is_reachable_even_when_the_account_is_unknown() {
        let dir = std::env::temp_dir().join(format!("protonvpn-gui-app-{}", std::process::id()));
        let config = Config {
            // No `curl` and no real CLI: this test is about a window state, not about running
            // anything.
            probe_enabled: false,
            ..Default::default()
        };
        let mut options =
            EngineOptions::new(ConfigStore::at(dir.join("config.json")), config.clone());
        options.program = dir.join("no-such-cli").to_string_lossy().into_owned();
        let engine = protonvpn_core::engine::spawn(options);
        let (_tx, rx) = std::sync::mpsc::channel::<TrayCommand>();

        let mut app = App::new(engine, config, rx, None, window::Settings::default());

        // Nothing has been observed yet. Unknown is not "signed out", so the app shows the window
        // rather than inventing a verdict and the login page is not forced.
        assert!(!app.signed_out());
        assert!(!app.login_was_forced());

        let _ = app.update(Message::SignInRequested);
        assert!(app.login_was_forced(), "the user asked to sign in");

        let _ = app.update(Message::SignInCancelled);
        assert!(!app.login_was_forced());
    }

    #[test]
    fn the_window_title_says_proton_vpn_and_never_protons_app_id() {
        // A reminder in code: this string is the window title, not a D-Bus name.
        assert_ne!("proton.vpn.app.gtk", "Proton VPN");
    }

    #[test]
    fn a_system_preset_is_exactly_the_cli_flag_it_names() {
        assert_eq!(SystemPreset::Fastest.target(), ConnectTarget::fastest());
        assert_eq!(
            Intent::Connect(SystemPreset::SecureCore.target()).argv(),
            vec!["protonvpn", "connect", "--securecore"]
        );
        assert_eq!(
            Intent::Connect(SystemPreset::P2p.target()).argv(),
            vec!["protonvpn", "connect", "--p2p"]
        );
        assert!(SystemPreset::P2p.target().port_forwarding);
    }

    #[test]
    fn a_selection_that_no_longer_resolves_connects_but_does_not_lie() {
        let config = Config {
            selected_connection: Some("gone".into()),
            ..Default::default()
        };
        assert_eq!(selected_target(&config), ConnectTarget::fastest());
    }
}
